# -*- coding: utf-8 -*-
"""product reviews project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Js0hFIa8RRnS-Lv4lp21Wr3_TkMuDXlW
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

#load sentiment analysis model
sentiment = pipeline("sentiment-analysis")

# sample product reviewn(you can change this text later)
reviews = """The laptop starts quickly and works smoothly  for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Overall, it is good laptop for students but not for gaming.
"""

# split review in to sentences
sentences = reviews.split(".")

pros = []
cons = []

for s in sentences:
  s = s.strip()
  if s == "":
    continue


  result = sentiment(s)[0]

  if result["label"] == "POSITIVE":
    pros.append(s)

  elif result["label"] == "NEGATIVE":
    cons.append(s)


# Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

# creayte table
df = pd.DataFrame({
    "pros": pros,
    "cons": cons



})


df