# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bv3f46ngznZBWeqyMhtYeLxfvmbqm4ar
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

#load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

# take input from user
text1 = input("enter text 1: ")
text2 = input("enter text 2: ")

# convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

# calculate similarity
similarity = util.cos_sim(embedding1, embedding2)

# show result
print("\nsimilarity score:", round(float(similarity),2))

if similarity > 0.75:
  print("similarity level: High")
elif similarity > 0.4:
  print("similarity level: Medium")
else:
  print("similarity level: Low")